{
 "title": "hidra_dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "sample",
    "query": {
     "query": "query_result(hidra_http_response_time{job=\"$job\"})"
    }
   },
   {
    "name": "job",
    "query": {
     "query": "query_result(hidra_http_response_time)"
    }
   }
  ]
 },
 "panels": [
  { "title": "$sample", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "sample" },
  {
   "title": "Statuses",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "hidra_sample_status{job=\"$job\", sample_name=\"$sample\"}",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Traceroute",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 13, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "hidra_icmp_traceroute_distance{sample_name=\"$sample\", job=\"$job\"}",
     "legendFormat": "{{instance}} -> {{hostname}} -> {{hop}}"
    }
   ]
  },
  {
   "title": "Hops",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 11, "x": 13, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(hidra_icmp_traceroute_ip{sample_name=\"$sample\", job=\"$job\"}) by (sample_name)",
     "legendFormat": "{{sample_name}}"
    }
   ]
  },
  {
   "title": "Response time by time",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 13, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "hidra_http_response_dns_time{sample_name=\"$sample\", job=\"$job\"}",
     "legendFormat": "[DNS] {{method}} {{url}} | {{ description }} ({{sample_name}})"
    },
    {
     "expr": "hidra_http_response_tcp_connect_time{sample_name=\"$sample\", job=\"$job\"}",
     "legendFormat": "[TCP] {{method}} {{url}} | {{ description }} ({{sample_name}})"
    },
    {
     "expr": "hidra_http_response_tls_handshake_time{sample_name=\"$sample\", job=\"$job\"}",
     "legendFormat": "[TLS] {{method}} {{url}} | {{ description }} ({{sample_name}})"
    },
    {
     "expr": "hidra_http_response_time{sample_name=\"$sample\", job=\"$job\"} - hidra_http_response_dns_time{sample_name=\"$sample\", job=\"$job\"} - hidra_http_response_tcp_connect_time{sample_name=\"$sample\", job=\"$job\"} - hidra_http_response_tls_handshake_time{sample_name=\"$sample\", job=\"$job\"}",
     "legendFormat": "[The rest] {{method}} {{url}} | {{ description }} ({{sample_name}})"
    }
   ]
  },
  {
   "title": "Response status code by time",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 11, "x": 13, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "hidra_http_response_status_code{sample_name=\"$sample\", job=\"$job\"}",
     "legendFormat": "{{method}} {{url}} | {{ description }} ({{sample_name}})"
    }
   ]
  },
  {
   "title": "Response size by time",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 13, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "hidra_http_response_content_length{sample_name=\"$sample\", job=\"$job\"}",
     "legendFormat": "{{method}} {{url}} | {{ description }} ({{sample_name}})"
    }
   ]
  },
  {
   "title": "Download speed",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 11, "x": 13, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "hidra_http_response_content_length{sample_name=\"$sample\", job=\"$job\"} / hidra_http_response_time{sample_name=\"$sample\", job=\"$job\"}",
     "legendFormat": "{{method}} {{url}} | {{ description }} ({{sample_name}})"
    }
   ]
  }
 ]
}