{
 "title": "principal_dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(hidra_sample_status)" }
   ]
  },
  {
   "title": "HTTP Estado",
   "type": "table",
   "gridPos": { "h": 15, "w": 20, "x": 4, "y": 0 },
   "targets": [
    {
     "expr": "hidra_sample_status{job=\"hidra-exporter\"}"
    },
    {
     "expr": "(hidra_tls_certificate_not_after{job=\"hidra-exporter\"}- time()) / 3600 / 24"
    },
    {
     "expr": "hidra_http_response_status_code{job=\"hidra-exporter\"}"
    },
    {
     "expr": "avg_over_time(hidra_http_response_time{job=\"hidra-exporter\"}[1m])"
    },
    {
     "expr": "hidra_tls_certificate_version{job=\"hidra-exporter\"}"
    },
    {
     "expr": "avg_over_time(hidra_http_response_dns_time{job=\"hidra-exporter\"}[1m])"
    }
   ]
  },
  {
   "title": "Success",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(hidra_sample_status == 1)"
    }
   ]
  },
  {
   "title": "Fail",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(hidra_sample_status == 0)"
    }
   ]
  },
  {
   "title": "Proporción de estado",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(hidra_sample_status{job=\"hidra-exporter\"} == 1)",
     "legendFormat": "SUCCESS"
    },
    {
     "expr": "count(hidra_sample_status{job=\"hidra-exporter\"} == 0)",
     "legendFormat": "FAIL"
    }
   ]
  },
  {
   "title": "HTTP Tiempo de respuesta",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(hidra_http_response_time{job=\"hidra-exporter\"}) by (url)"
    }
   ]
  },
  {
   "title": "DNS Tiempo de respuesta",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(hidra_http_response_dns_time{job=\"hidra-exporter\"}) by (url)"
    }
   ]
  }
 ]
}