global:
  scrape_interval: 1m
scrape_configs:
  - job_name: "hidra-exporter"
    scrape_interval: 1m
    static_configs:
      - targets: ["hidra:19090"]
    basic_auth:
      username: "admin"
      password_file: "/etc/prometheus/passwdweb"
